// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
)

const creatUser = `-- name: CreatUser :one
INSERT INTO users DEFAULT VALUES RETURNING id, balance
`

func (q *Queries) CreatUser(ctx context.Context) (User, error) {
	row := q.db.QueryRowContext(ctx, creatUser)
	var i User
	err := row.Scan(&i.ID, &i.Balance)
	return i, err
}

const deductBalance = `-- name: DeductBalance :execrows
UPDATE users SET balance = balance - $2 WHERE id = $1 AND balance >= $2
`

type DeductBalanceParams struct {
	ID      int64
	Balance int32
}

func (q *Queries) DeductBalance(ctx context.Context, arg DeductBalanceParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deductBalance, arg.ID, arg.Balance)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getUser = `-- name: GetUser :one
SELECT id, balance FROM users WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i User
	err := row.Scan(&i.ID, &i.Balance)
	return i, err
}
