// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
)

const creatUser = `-- name: CreatUser :one
INSERT INTO users DEFAULT VALUES RETURNING id
`

func (q *Queries) CreatUser(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, creatUser)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getUser = `-- name: GetUser :one
SELECT id FROM users WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var id_2 int64
	err := row.Scan(&id_2)
	return id_2, err
}
