// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: b.proto

package b

import (
	"context"

	"svc-b/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	PingReq  = pb.PingReq
	PingResp = pb.PingResp
	PongReq  = pb.PongReq
	PongResp = pb.PongResp

	B interface {
		Ping(ctx context.Context, in *PingReq, opts ...grpc.CallOption) (*PingResp, error)
		Pong(ctx context.Context, in *PongReq, opts ...grpc.CallOption) (*PongResp, error)
	}

	defaultB struct {
		cli zrpc.Client
	}
)

func NewB(cli zrpc.Client) B {
	return &defaultB{
		cli: cli,
	}
}

func (m *defaultB) Ping(ctx context.Context, in *PingReq, opts ...grpc.CallOption) (*PingResp, error) {
	client := pb.NewBClient(m.cli.Conn())
	return client.Ping(ctx, in, opts...)
}

func (m *defaultB) Pong(ctx context.Context, in *PongReq, opts ...grpc.CallOption) (*PongResp, error) {
	client := pb.NewBClient(m.cli.Conn())
	return client.Pong(ctx, in, opts...)
}
