// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: api/user/v1/user_error.proto

package v1

import (
	_ "github.com/go-kratos/kratos/v2/errors"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserErrorReason int32

const (
	UserErrorReason_USER_NOT_FOUND UserErrorReason = 0
	UserErrorReason_LOW_BALANCE    UserErrorReason = 1
)

// Enum value maps for UserErrorReason.
var (
	UserErrorReason_name = map[int32]string{
		0: "USER_NOT_FOUND",
		1: "LOW_BALANCE",
	}
	UserErrorReason_value = map[string]int32{
		"USER_NOT_FOUND": 0,
		"LOW_BALANCE":    1,
	}
)

func (x UserErrorReason) Enum() *UserErrorReason {
	p := new(UserErrorReason)
	*p = x
	return p
}

func (x UserErrorReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserErrorReason) Descriptor() protoreflect.EnumDescriptor {
	return file_api_user_v1_user_error_proto_enumTypes[0].Descriptor()
}

func (UserErrorReason) Type() protoreflect.EnumType {
	return &file_api_user_v1_user_error_proto_enumTypes[0]
}

func (x UserErrorReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserErrorReason.Descriptor instead.
func (UserErrorReason) EnumDescriptor() ([]byte, []int) {
	return file_api_user_v1_user_error_proto_rawDescGZIP(), []int{0}
}

var File_api_user_v1_user_error_proto protoreflect.FileDescriptor

const file_api_user_v1_user_error_proto_rawDesc = "" +
	"\n" +
	"\x1capi/user/v1/user_error.proto\x12\vapi.user.v1\x1a\x13errors/errors.proto*H\n" +
	"\x0fUserErrorReason\x12\x18\n" +
	"\x0eUSER_NOT_FOUND\x10\x00\x1a\x04\xa8E\x94\x03\x12\x15\n" +
	"\vLOW_BALANCE\x10\x01\x1a\x04\xa8E\x90\x03\x1a\x04\xa0E\xf4\x03B\x18Z\x16seckill/api/user/v1;v1b\x06proto3"

var (
	file_api_user_v1_user_error_proto_rawDescOnce sync.Once
	file_api_user_v1_user_error_proto_rawDescData []byte
)

func file_api_user_v1_user_error_proto_rawDescGZIP() []byte {
	file_api_user_v1_user_error_proto_rawDescOnce.Do(func() {
		file_api_user_v1_user_error_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_user_v1_user_error_proto_rawDesc), len(file_api_user_v1_user_error_proto_rawDesc)))
	})
	return file_api_user_v1_user_error_proto_rawDescData
}

var file_api_user_v1_user_error_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_user_v1_user_error_proto_goTypes = []any{
	(UserErrorReason)(0), // 0: api.user.v1.UserErrorReason
}
var file_api_user_v1_user_error_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_user_v1_user_error_proto_init() }
func file_api_user_v1_user_error_proto_init() {
	if File_api_user_v1_user_error_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_user_v1_user_error_proto_rawDesc), len(file_api_user_v1_user_error_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_user_v1_user_error_proto_goTypes,
		DependencyIndexes: file_api_user_v1_user_error_proto_depIdxs,
		EnumInfos:         file_api_user_v1_user_error_proto_enumTypes,
	}.Build()
	File_api_user_v1_user_error_proto = out.File
	file_api_user_v1_user_error_proto_goTypes = nil
	file_api_user_v1_user_error_proto_depIdxs = nil
}
