apiVersion: v1
kind: Service
metadata:
  labels:
    app: user
  name: user
spec:
  ports:
    - name: http
      port: 8000
      targetPort: 8000
    - name: grpc
      port: 9000
      targetPort: 9000
  selector:
    app: user
