// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: post.proto

package post

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetpostbyuserReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Userid        int64                  `protobuf:"varint,1,opt,name=userid,proto3" json:"userid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetpostbyuserReq) Reset() {
	*x = GetpostbyuserReq{}
	mi := &file_post_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetpostbyuserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetpostbyuserReq) ProtoMessage() {}

func (x *GetpostbyuserReq) ProtoReflect() protoreflect.Message {
	mi := &file_post_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetpostbyuserReq.ProtoReflect.Descriptor instead.
func (*GetpostbyuserReq) Descriptor() ([]byte, []int) {
	return file_post_proto_rawDescGZIP(), []int{0}
}

func (x *GetpostbyuserReq) GetUserid() int64 {
	if x != nil {
		return x.Userid
	}
	return 0
}

type GetpostbyuserResp struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Posts         []*GetpostbyuserResp_Post `protobuf:"bytes,1,rep,name=posts,proto3" json:"posts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetpostbyuserResp) Reset() {
	*x = GetpostbyuserResp{}
	mi := &file_post_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetpostbyuserResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetpostbyuserResp) ProtoMessage() {}

func (x *GetpostbyuserResp) ProtoReflect() protoreflect.Message {
	mi := &file_post_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetpostbyuserResp.ProtoReflect.Descriptor instead.
func (*GetpostbyuserResp) Descriptor() ([]byte, []int) {
	return file_post_proto_rawDescGZIP(), []int{1}
}

func (x *GetpostbyuserResp) GetPosts() []*GetpostbyuserResp_Post {
	if x != nil {
		return x.Posts
	}
	return nil
}

type GetpostReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetpostReq) Reset() {
	*x = GetpostReq{}
	mi := &file_post_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetpostReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetpostReq) ProtoMessage() {}

func (x *GetpostReq) ProtoReflect() protoreflect.Message {
	mi := &file_post_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetpostReq.ProtoReflect.Descriptor instead.
func (*GetpostReq) Descriptor() ([]byte, []int) {
	return file_post_proto_rawDescGZIP(), []int{2}
}

func (x *GetpostReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetpostResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Posts         []*GetpostResp_Post    `protobuf:"bytes,1,rep,name=posts,proto3" json:"posts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetpostResp) Reset() {
	*x = GetpostResp{}
	mi := &file_post_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetpostResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetpostResp) ProtoMessage() {}

func (x *GetpostResp) ProtoReflect() protoreflect.Message {
	mi := &file_post_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetpostResp.ProtoReflect.Descriptor instead.
func (*GetpostResp) Descriptor() ([]byte, []int) {
	return file_post_proto_rawDescGZIP(), []int{3}
}

func (x *GetpostResp) GetPosts() []*GetpostResp_Post {
	if x != nil {
		return x.Posts
	}
	return nil
}

type GetpostbyuserResp_Post struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetpostbyuserResp_Post) Reset() {
	*x = GetpostbyuserResp_Post{}
	mi := &file_post_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetpostbyuserResp_Post) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetpostbyuserResp_Post) ProtoMessage() {}

func (x *GetpostbyuserResp_Post) ProtoReflect() protoreflect.Message {
	mi := &file_post_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetpostbyuserResp_Post.ProtoReflect.Descriptor instead.
func (*GetpostbyuserResp_Post) Descriptor() ([]byte, []int) {
	return file_post_proto_rawDescGZIP(), []int{1, 0}
}

func (x *GetpostbyuserResp_Post) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetpostbyuserResp_Post) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetpostResp_Post struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetpostResp_Post) Reset() {
	*x = GetpostResp_Post{}
	mi := &file_post_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetpostResp_Post) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetpostResp_Post) ProtoMessage() {}

func (x *GetpostResp_Post) ProtoReflect() protoreflect.Message {
	mi := &file_post_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetpostResp_Post.ProtoReflect.Descriptor instead.
func (*GetpostResp_Post) Descriptor() ([]byte, []int) {
	return file_post_proto_rawDescGZIP(), []int{3, 0}
}

func (x *GetpostResp_Post) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetpostResp_Post) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_post_proto protoreflect.FileDescriptor

const file_post_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"post.proto\x12\x04post\"*\n" +
	"\x10GetpostbyuserReq\x12\x16\n" +
	"\x06userid\x18\x01 \x01(\x03R\x06userid\"s\n" +
	"\x11GetpostbyuserResp\x122\n" +
	"\x05posts\x18\x01 \x03(\v2\x1c.post.GetpostbyuserResp.PostR\x05posts\x1a*\n" +
	"\x04Post\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\x1c\n" +
	"\n" +
	"GetpostReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"g\n" +
	"\vGetpostResp\x12,\n" +
	"\x05posts\x18\x01 \x03(\v2\x16.post.GetpostResp.PostR\x05posts\x1a*\n" +
	"\x04Post\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name2x\n" +
	"\x04Post\x12@\n" +
	"\rGetpostbyuser\x12\x16.post.GetpostbyuserReq\x1a\x17.post.GetpostbyuserResp\x12.\n" +
	"\aGetpost\x12\x10.post.GetpostReq\x1a\x11.post.GetpostRespB\bZ\x06./postb\x06proto3"

var (
	file_post_proto_rawDescOnce sync.Once
	file_post_proto_rawDescData []byte
)

func file_post_proto_rawDescGZIP() []byte {
	file_post_proto_rawDescOnce.Do(func() {
		file_post_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_post_proto_rawDesc), len(file_post_proto_rawDesc)))
	})
	return file_post_proto_rawDescData
}

var file_post_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_post_proto_goTypes = []any{
	(*GetpostbyuserReq)(nil),       // 0: post.GetpostbyuserReq
	(*GetpostbyuserResp)(nil),      // 1: post.GetpostbyuserResp
	(*GetpostReq)(nil),             // 2: post.GetpostReq
	(*GetpostResp)(nil),            // 3: post.GetpostResp
	(*GetpostbyuserResp_Post)(nil), // 4: post.GetpostbyuserResp.Post
	(*GetpostResp_Post)(nil),       // 5: post.GetpostResp.Post
}
var file_post_proto_depIdxs = []int32{
	4, // 0: post.GetpostbyuserResp.posts:type_name -> post.GetpostbyuserResp.Post
	5, // 1: post.GetpostResp.posts:type_name -> post.GetpostResp.Post
	0, // 2: post.Post.Getpostbyuser:input_type -> post.GetpostbyuserReq
	2, // 3: post.Post.Getpost:input_type -> post.GetpostReq
	1, // 4: post.Post.Getpostbyuser:output_type -> post.GetpostbyuserResp
	3, // 5: post.Post.Getpost:output_type -> post.GetpostResp
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_post_proto_init() }
func file_post_proto_init() {
	if File_post_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_post_proto_rawDesc), len(file_post_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_post_proto_goTypes,
		DependencyIndexes: file_post_proto_depIdxs,
		MessageInfos:      file_post_proto_msgTypes,
	}.Build()
	File_post_proto = out.File
	file_post_proto_goTypes = nil
	file_post_proto_depIdxs = nil
}
