// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: a.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CallAReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallAReq) Reset() {
	*x = CallAReq{}
	mi := &file_a_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallAReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallAReq) ProtoMessage() {}

func (x *CallAReq) ProtoReflect() protoreflect.Message {
	mi := &file_a_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallAReq.ProtoReflect.Descriptor instead.
func (*CallAReq) Descriptor() ([]byte, []int) {
	return file_a_proto_rawDescGZIP(), []int{0}
}

type CallAResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallAResp) Reset() {
	*x = CallAResp{}
	mi := &file_a_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallAResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallAResp) ProtoMessage() {}

func (x *CallAResp) ProtoReflect() protoreflect.Message {
	mi := &file_a_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallAResp.ProtoReflect.Descriptor instead.
func (*CallAResp) Descriptor() ([]byte, []int) {
	return file_a_proto_rawDescGZIP(), []int{1}
}

func (x *CallAResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_a_proto protoreflect.FileDescriptor

const file_a_proto_rawDesc = "" +
	"\n" +
	"\aa.proto\x12\x02pb\"\n" +
	"\n" +
	"\bCallAReq\"\x1d\n" +
	"\tCallAResp\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg2)\n" +
	"\x01A\x12$\n" +
	"\x05CallA\x12\f.pb.CallAReq\x1a\r.pb.CallARespB\x06Z\x04./pbb\x06proto3"

var (
	file_a_proto_rawDescOnce sync.Once
	file_a_proto_rawDescData []byte
)

func file_a_proto_rawDescGZIP() []byte {
	file_a_proto_rawDescOnce.Do(func() {
		file_a_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_a_proto_rawDesc), len(file_a_proto_rawDesc)))
	})
	return file_a_proto_rawDescData
}

var file_a_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_a_proto_goTypes = []any{
	(*CallAReq)(nil),  // 0: pb.CallAReq
	(*CallAResp)(nil), // 1: pb.CallAResp
}
var file_a_proto_depIdxs = []int32{
	0, // 0: pb.A.CallA:input_type -> pb.CallAReq
	1, // 1: pb.A.CallA:output_type -> pb.CallAResp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_a_proto_init() }
func file_a_proto_init() {
	if File_a_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_a_proto_rawDesc), len(file_a_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_a_proto_goTypes,
		DependencyIndexes: file_a_proto_depIdxs,
		MessageInfos:      file_a_proto_msgTypes,
	}.Build()
	File_a_proto = out.File
	file_a_proto_goTypes = nil
	file_a_proto_depIdxs = nil
}
