// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: a.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	A_CallA_FullMethodName = "/pb.A/CallA"
)

// AClient is the client API for A service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AClient interface {
	CallA(ctx context.Context, in *CallAReq, opts ...grpc.CallOption) (*CallAResp, error)
}

type aClient struct {
	cc grpc.ClientConnInterface
}

func NewAClient(cc grpc.ClientConnInterface) AClient {
	return &aClient{cc}
}

func (c *aClient) CallA(ctx context.Context, in *CallAReq, opts ...grpc.CallOption) (*CallAResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CallAResp)
	err := c.cc.Invoke(ctx, A_CallA_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AServer is the server API for A service.
// All implementations must embed UnimplementedAServer
// for forward compatibility.
type AServer interface {
	CallA(context.Context, *CallAReq) (*CallAResp, error)
	mustEmbedUnimplementedAServer()
}

// UnimplementedAServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAServer struct{}

func (UnimplementedAServer) CallA(context.Context, *CallAReq) (*CallAResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CallA not implemented")
}
func (UnimplementedAServer) mustEmbedUnimplementedAServer() {}
func (UnimplementedAServer) testEmbeddedByValue()           {}

// UnsafeAServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AServer will
// result in compilation errors.
type UnsafeAServer interface {
	mustEmbedUnimplementedAServer()
}

func RegisterAServer(s grpc.ServiceRegistrar, srv AServer) {
	// If the following call panics, it indicates UnimplementedAServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&A_ServiceDesc, srv)
}

func _A_CallA_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CallAReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AServer).CallA(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: A_CallA_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AServer).CallA(ctx, req.(*CallAReq))
	}
	return interceptor(ctx, in, info, handler)
}

// A_ServiceDesc is the grpc.ServiceDesc for A service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var A_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.A",
	HandlerType: (*AServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CallA",
			Handler:    _A_CallA_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "a.proto",
}
