// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"svc-a/internal/conf"
	"svc-a/internal/server"
	"svc-a/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, registry *conf.Registry, logger log.Logger) (*kratos.App, func(), error) {
	etcdClient := server.NewEtcdClient(registry)
	discovery := server.NewDiscovery(etcdClient)
	bClient := server.NewBClient(discovery)
	greeterService := service.NewGreeterService(bClient)
	grpcServer := server.NewGRPCServer(confServer, greeterService, logger)
	httpServer := server.NewHTTPServer(confServer, greeterService, logger)
	registrar := server.NewRegistrar(etcdClient)
	app := newApp(logger, grpcServer, httpServer, registrar)
	return app, func() {}, nil
}
