// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: a.proto

package server

import (
	"context"

	"github.com/Dailiduzhou/weeklyLearningJournal/semester2/week6/micro_svc/svc-a/internal/logic"
	"github.com/Dailiduzhou/weeklyLearningJournal/semester2/week6/micro_svc/svc-a/internal/svc"
	"github.com/Dailiduzhou/weeklyLearningJournal/semester2/week6/micro_svc/svc-a/pb"
)

type AServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedAServer
}

func NewAServer(svcCtx *svc.ServiceContext) *AServer {
	return &AServer{
		svcCtx: svcCtx,
	}
}

func (s *AServer) CallA(ctx context.Context, in *pb.CallAReq) (*pb.CallAResp, error) {
	l := logic.NewCallALogic(ctx, s.svcCtx)
	return l.CallA(in)
}
