// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.1
// source: proto/service.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TikerService_GetStockUpdates_FullMethodName = "/TikerService/GetStockUpdates"
	TikerService_Chat_FullMethodName            = "/TikerService/Chat"
)

// TikerServiceClient is the client API for TikerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TikerServiceClient interface {
	GetStockUpdates(ctx context.Context, in *StockRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StockPrice], error)
	Chat(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ChatMessage, ChatMessage], error)
}

type tikerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTikerServiceClient(cc grpc.ClientConnInterface) TikerServiceClient {
	return &tikerServiceClient{cc}
}

func (c *tikerServiceClient) GetStockUpdates(ctx context.Context, in *StockRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StockPrice], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TikerService_ServiceDesc.Streams[0], TikerService_GetStockUpdates_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StockRequest, StockPrice]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TikerService_GetStockUpdatesClient = grpc.ServerStreamingClient[StockPrice]

func (c *tikerServiceClient) Chat(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ChatMessage, ChatMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TikerService_ServiceDesc.Streams[1], TikerService_Chat_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ChatMessage, ChatMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TikerService_ChatClient = grpc.BidiStreamingClient[ChatMessage, ChatMessage]

// TikerServiceServer is the server API for TikerService service.
// All implementations must embed UnimplementedTikerServiceServer
// for forward compatibility.
type TikerServiceServer interface {
	GetStockUpdates(*StockRequest, grpc.ServerStreamingServer[StockPrice]) error
	Chat(grpc.BidiStreamingServer[ChatMessage, ChatMessage]) error
	mustEmbedUnimplementedTikerServiceServer()
}

// UnimplementedTikerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTikerServiceServer struct{}

func (UnimplementedTikerServiceServer) GetStockUpdates(*StockRequest, grpc.ServerStreamingServer[StockPrice]) error {
	return status.Error(codes.Unimplemented, "method GetStockUpdates not implemented")
}
func (UnimplementedTikerServiceServer) Chat(grpc.BidiStreamingServer[ChatMessage, ChatMessage]) error {
	return status.Error(codes.Unimplemented, "method Chat not implemented")
}
func (UnimplementedTikerServiceServer) mustEmbedUnimplementedTikerServiceServer() {}
func (UnimplementedTikerServiceServer) testEmbeddedByValue()                      {}

// UnsafeTikerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TikerServiceServer will
// result in compilation errors.
type UnsafeTikerServiceServer interface {
	mustEmbedUnimplementedTikerServiceServer()
}

func RegisterTikerServiceServer(s grpc.ServiceRegistrar, srv TikerServiceServer) {
	// If the following call panics, it indicates UnimplementedTikerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TikerService_ServiceDesc, srv)
}

func _TikerService_GetStockUpdates_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StockRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TikerServiceServer).GetStockUpdates(m, &grpc.GenericServerStream[StockRequest, StockPrice]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TikerService_GetStockUpdatesServer = grpc.ServerStreamingServer[StockPrice]

func _TikerService_Chat_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TikerServiceServer).Chat(&grpc.GenericServerStream[ChatMessage, ChatMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TikerService_ChatServer = grpc.BidiStreamingServer[ChatMessage, ChatMessage]

// TikerService_ServiceDesc is the grpc.ServiceDesc for TikerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TikerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "TikerService",
	HandlerType: (*TikerServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetStockUpdates",
			Handler:       _TikerService_GetStockUpdates_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Chat",
			Handler:       _TikerService_Chat_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/service.proto",
}
