// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: user.proto

package post

import (
	"context"

	"zero-service/user/user"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GetpostReq       = user.GetpostReq
	GetpostResp      = user.GetpostResp
	GetpostResp_Post = user.GetpostResp_Post

	Post interface {
		Getpost(ctx context.Context, in *GetpostReq, opts ...grpc.CallOption) (*GetpostResp, error)
	}

	defaultPost struct {
		cli zrpc.Client
	}
)

func NewPost(cli zrpc.Client) Post {
	return &defaultPost{
		cli: cli,
	}
}

func (m *defaultPost) Getpost(ctx context.Context, in *GetpostReq, opts ...grpc.CallOption) (*GetpostResp, error) {
	client := user.NewPostClient(m.cli.Conn())
	return client.Getpost(ctx, in, opts...)
}
