// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v7.34.1
// source: product/v1/product.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationProductSeckill = "/api.product.v1.Product/Seckill"

type ProductHTTPServer interface {
	Seckill(context.Context, *SeckillReq) (*SeckillResp, error)
}

func RegisterProductHTTPServer(s *http.Server, srv ProductHTTPServer) {
	r := s.Route("/")
	r.POST("/api/seckill", _Product_Seckill0_HTTP_Handler(srv))
}

func _Product_Seckill0_HTTP_Handler(srv ProductHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SeckillReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProductSeckill)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Seckill(ctx, req.(*SeckillReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SeckillResp)
		return ctx.Result(200, reply)
	}
}

type ProductHTTPClient interface {
	Seckill(ctx context.Context, req *SeckillReq, opts ...http.CallOption) (rsp *SeckillResp, err error)
}

type ProductHTTPClientImpl struct {
	cc *http.Client
}

func NewProductHTTPClient(client *http.Client) ProductHTTPClient {
	return &ProductHTTPClientImpl{client}
}

func (c *ProductHTTPClientImpl) Seckill(ctx context.Context, in *SeckillReq, opts ...http.CallOption) (*SeckillResp, error) {
	var out SeckillResp
	pattern := "/api/seckill"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationProductSeckill))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
