// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: a.proto

package a

import (
	"context"

	"svc-a/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CallAReq  = pb.CallAReq
	CallAResp = pb.CallAResp

	A interface {
		CallA(ctx context.Context, in *CallAReq, opts ...grpc.CallOption) (*CallAResp, error)
	}

	defaultA struct {
		cli zrpc.Client
	}
)

func NewA(cli zrpc.Client) A {
	return &defaultA{
		cli: cli,
	}
}

func (m *defaultA) CallA(ctx context.Context, in *CallAReq, opts ...grpc.CallOption) (*CallAResp, error) {
	client := pb.NewAClient(m.cli.Conn())
	return client.CallA(ctx, in, opts...)
}
