// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: post.proto

package postclient

import (
	"context"

	"github.com/Dailiduzhou/weeklyLearningJournal/semester2/week10/zero-service/post/post/post"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GetpostReq       = post.GetpostReq
	GetpostResp      = post.GetpostResp
	GetpostResp_Post = post.GetpostResp_Post

	Post interface {
		Getpost(ctx context.Context, in *GetpostReq, opts ...grpc.CallOption) (*GetpostResp, error)
	}

	defaultPost struct {
		cli zrpc.Client
	}
)

func NewPost(cli zrpc.Client) Post {
	return &defaultPost{
		cli: cli,
	}
}

func (m *defaultPost) Getpost(ctx context.Context, in *GetpostReq, opts ...grpc.CallOption) (*GetpostResp, error) {
	client := post.NewPostClient(m.cli.Conn())
	return client.Getpost(ctx, in, opts...)
}
