// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
)

const deductStock = `-- name: DeductStock :execrows
UPDATE products SET stock = stock - $2 WHERE id = $1 AND stock >= $2
`

type DeductStockParams struct {
	ID    int64
	Stock int32
}

func (q *Queries) DeductStock(ctx context.Context, arg DeductStockParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deductStock, arg.ID, arg.Stock)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getProduct = `-- name: GetProduct :one
SELECT id, price, stock FROM products WHERE id = $1 LIMIT 1
`

func (q *Queries) GetProduct(ctx context.Context, id int64) (Product, error) {
	row := q.db.QueryRowContext(ctx, getProduct, id)
	var i Product
	err := row.Scan(&i.ID, &i.Price, &i.Stock)
	return i, err
}
