// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"forum/config"
	"forum/controllers"
	"forum/repositories"
	"forum/services"
	"go.mongodb.org/mongo-driver/mongo"
)

// Injectors from wire.go:

func InitializeApplication(cfg *config.Config, db *mongo.Database) (*App, error) {
	userRepository := repositories.NewUserRepository(db)
	jwtConfig := provideJWTConfig(cfg)
	jwtService := services.NewJWTService(jwtConfig)
	userService := services.NewUserService(userRepository, jwtService)
	authController := controllers.NewAuthController(userService)
	postRepository := repositories.NewPostRepository(db)
	postService := services.NewPostService(postRepository)
	postController := controllers.NewPostController(postService)
	app := NewApp(authController, postController, jwtService)
	return app, nil
}
