// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type DeleteUserRequest struct {
	ID int64 `path:"id"`
}

type DeleteUserResp struct {
	ID       int64  `json:"id"`
	Username string `json:"id"`
}

type LoginRequest struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResp struct {
	Username string `json:"username"`
}

type RefreshRequest struct {
	RefreshToken string `json:"refresh_token"`
}

type RefreshResp struct {
	AccessToken  string `json:"access_token"`
	RefreshToken string `json:"refresh_token"`
}

type RegisterRequest struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type RegisterResp struct {
	Username string `json:"username"`
}

type UpdateUserRequest struct {
	ID       int64  `json:"id"`
	Username string `json:"username"`
}

type UpdateUserResp struct {
	ID       int64  `json:"id"`
	Username string `json:"username"`
}

type User struct {
	ID       int64  `json:"id"`
	Username string `json:"username"`
	Password string `json:"-"`
	Role     string `json:"role,options=user|admin"`
}

type UserInfoRequest struct {
	ID int64 `path:"id"`
}

type UserInfoResp struct {
	ID       int64  `json:"id"`
	Username string `json:"username"`
	Role     string `json:"role"`
}
