// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: user.proto

package server

import (
	"context"

	"zero-service/user/internal/logic"
	"zero-service/user/internal/svc"
	"zero-service/user/user"
)

type PostServer struct {
	svcCtx *svc.ServiceContext
	user.UnimplementedPostServer
}

func NewPostServer(svcCtx *svc.ServiceContext) *PostServer {
	return &PostServer{
		svcCtx: svcCtx,
	}
}

func (s *PostServer) Getpost(ctx context.Context, in *user.GetpostReq) (*user.GetpostResp, error) {
	l := logic.NewGetpostLogic(ctx, s.svcCtx)
	return l.Getpost(in)
}
