// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: user.proto

package server

import (
	"context"

	"github.com/Dailiduzhou/weeklyLearningJournal/semester2/week10/zero-service/user/internal/logic"
	"github.com/Dailiduzhou/weeklyLearningJournal/semester2/week10/zero-service/user/internal/svc"
	"github.com/Dailiduzhou/weeklyLearningJournal/semester2/week10/zero-service/user/user/user"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
	user.UnimplementedUserServer
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServer) Query(ctx context.Context, in *user.QueryReq) (*user.QueryResp, error) {
	l := logic.NewQueryLogic(ctx, s.svcCtx)
	return l.Query(in)
}
