# 开发环境 Dockerfile - 从项目根目录构建
# 构建命令: docker build -f svc-a/Dockerfile.dev .

FROM golang:1.24-alpine AS builder

ENV CGO_ENABLED=0
ENV GOOS=linux
ENV GOARCH=amd64
ENV GOPROXY=https://goproxy.cn,direct
WORKDIR /build

# 复制 svc-a 和 svc-b 源码
COPY svc-a ./svc-a
COPY svc-b ./svc-b

# 切换到 svc-a 目录进行构建
WORKDIR /build/svc-a

# 下载依赖并构建
RUN go mod download


RUN  go build -ldflags="-s -w" -o /app/server pb.go

# 运行阶段
FROM alpine:3.19

RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories && \
  apk add --no-cache ca-certificates tzdata curl

ENV TZ=Asia/Shanghai

WORKDIR /app

COPY --from=builder /app/server /app/server

EXPOSE 9001

CMD ["/app/server", "-f", "/app/etc/pb.yaml"]
