apiVersion: apps/v1
kind: Deployment
metadata:
  name: svc-a
  namespace: micro-svc
  labels:
    app: svc-a
spec:
  replicas: 3
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: svc-a
  template:
    metadata:
      labels:
        app: svc-a
    spec:
      containers:
      - name: svc-a
        image: svc-a:latest
        ports:
        - containerPort: 9001
        readinessProbe:
          tcpSocket:
            port: 9001
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 9001
          initialDelaySeconds: 15
          periodSeconds: 20
        resources:
          requests:
            cpu: 500m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 1024Mi
        volumeMounts:
        - name: timezone
          mountPath: /etc/localtime
      volumes:
        - name: timezone
          hostPath:
            path: /usr/share/zoneinfo/Asia/Shanghai

---

apiVersion: v1
kind: Service
metadata:
  name: svc-a-svc
  namespace: micro-svc
spec:
  ports:
  - port: 9001
    targetPort: 9001
  selector:
    app: svc-a

---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: svc-a-hpa-c
  namespace: micro-svc
  labels:
    app: svc-a-hpa-c
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: svc-a
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80

---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: svc-a-hpa-m
  namespace: micro-svc
  labels:
    app: svc-a-hpa-m
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: svc-a
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
