// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: post.proto

package server

import (
	"context"

	"github.com/Dailiduzhou/weeklyLearningJournal/semester2/week10/zero-service/post/internal/logic"
	"github.com/Dailiduzhou/weeklyLearningJournal/semester2/week10/zero-service/post/internal/svc"
	"github.com/Dailiduzhou/weeklyLearningJournal/semester2/week10/zero-service/post/post/post"
)

type PostServer struct {
	svcCtx *svc.ServiceContext
	post.UnimplementedPostServer
}

func NewPostServer(svcCtx *svc.ServiceContext) *PostServer {
	return &PostServer{
		svcCtx: svcCtx,
	}
}

func (s *PostServer) Getpost(ctx context.Context, in *post.GetpostReq) (*post.GetpostResp, error) {
	l := logic.NewGetpostLogic(ctx, s.svcCtx)
	return l.Getpost(in)
}
