// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: helloworld/a/v1/greeter.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PingReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingReq) Reset() {
	*x = PingReq{}
	mi := &file_helloworld_a_v1_greeter_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingReq) ProtoMessage() {}

func (x *PingReq) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_a_v1_greeter_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingReq.ProtoReflect.Descriptor instead.
func (*PingReq) Descriptor() ([]byte, []int) {
	return file_helloworld_a_v1_greeter_proto_rawDescGZIP(), []int{0}
}

type PingResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResp) Reset() {
	*x = PingResp{}
	mi := &file_helloworld_a_v1_greeter_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResp) ProtoMessage() {}

func (x *PingResp) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_a_v1_greeter_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResp.ProtoReflect.Descriptor instead.
func (*PingResp) Descriptor() ([]byte, []int) {
	return file_helloworld_a_v1_greeter_proto_rawDescGZIP(), []int{1}
}

func (x *PingResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_helloworld_a_v1_greeter_proto protoreflect.FileDescriptor

const file_helloworld_a_v1_greeter_proto_rawDesc = "" +
	"\n" +
	"\x1dhelloworld/a/v1/greeter.proto\x12\x0fhelloworld.a.v1\x1a\x1cgoogle/api/annotations.proto\"\t\n" +
	"\aPingReq\"\x1c\n" +
	"\bPingResp\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg2O\n" +
	"\x01A\x12J\n" +
	"\x04Ping\x12\x18.helloworld.a.v1.PingReq\x1a\x19.helloworld.a.v1.PingResp\"\r\x82\xd3\xe4\x93\x02\a\x12\x05/pingBS\n" +
	"\x1edev.kratos.api.helloworld.a.v1B\x11HelloworldProtoV1P\x01Z\x1csvc-a/api/helloworld/a/v1;v1b\x06proto3"

var (
	file_helloworld_a_v1_greeter_proto_rawDescOnce sync.Once
	file_helloworld_a_v1_greeter_proto_rawDescData []byte
)

func file_helloworld_a_v1_greeter_proto_rawDescGZIP() []byte {
	file_helloworld_a_v1_greeter_proto_rawDescOnce.Do(func() {
		file_helloworld_a_v1_greeter_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_helloworld_a_v1_greeter_proto_rawDesc), len(file_helloworld_a_v1_greeter_proto_rawDesc)))
	})
	return file_helloworld_a_v1_greeter_proto_rawDescData
}

var file_helloworld_a_v1_greeter_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_helloworld_a_v1_greeter_proto_goTypes = []any{
	(*PingReq)(nil),  // 0: helloworld.a.v1.PingReq
	(*PingResp)(nil), // 1: helloworld.a.v1.PingResp
}
var file_helloworld_a_v1_greeter_proto_depIdxs = []int32{
	0, // 0: helloworld.a.v1.A.Ping:input_type -> helloworld.a.v1.PingReq
	1, // 1: helloworld.a.v1.A.Ping:output_type -> helloworld.a.v1.PingResp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_helloworld_a_v1_greeter_proto_init() }
func file_helloworld_a_v1_greeter_proto_init() {
	if File_helloworld_a_v1_greeter_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_helloworld_a_v1_greeter_proto_rawDesc), len(file_helloworld_a_v1_greeter_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_helloworld_a_v1_greeter_proto_goTypes,
		DependencyIndexes: file_helloworld_a_v1_greeter_proto_depIdxs,
		MessageInfos:      file_helloworld_a_v1_greeter_proto_msgTypes,
	}.Build()
	File_helloworld_a_v1_greeter_proto = out.File
	file_helloworld_a_v1_greeter_proto_goTypes = nil
	file_helloworld_a_v1_greeter_proto_depIdxs = nil
}
