// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: b.proto

package server

import (
	"context"

	"github.com/Dailiduzhou/weeklyLearningJournal/semester2/week6/micro_svc/svc-b/internal/logic"
	"github.com/Dailiduzhou/weeklyLearningJournal/semester2/week6/micro_svc/svc-b/internal/svc"
	"github.com/Dailiduzhou/weeklyLearningJournal/semester2/week6/micro_svc/svc-b/pb"
)

type BServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedBServer
}

func NewBServer(svcCtx *svc.ServiceContext) *BServer {
	return &BServer{
		svcCtx: svcCtx,
	}
}

func (s *BServer) Ping(ctx context.Context, in *pb.PingReq) (*pb.PingResp, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
