// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"net/http"

	user "crud/cmd/internal/handler/user"
	"crud/cmd/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// Refresh token
				Method:  http.MethodPost,
				Path:    "/user/refresh",
				Handler: user.RefreshHandler(serverCtx),
			},
			{
				// Register
				Method:  http.MethodPost,
				Path:    "/user/register",
				Handler: user.RegisterHandler(serverCtx),
			},
			{
				// Login
				Method:  http.MethodPost,
				Path:    "/user/register",
				Handler: user.LoginHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// Get users's info
				Method:  http.MethodGet,
				Path:    "/user/:id",
				Handler: user.DetailHandler(serverCtx),
			},
			{
				// Update user's profile
				Method:  http.MethodPost,
				Path:    "/user/update",
				Handler: user.UpdateHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AdminMiddleware},
			[]rest.Route{
				{
					// Delete a user
					Method:  http.MethodPost,
					Path:    "/user/:id",
					Handler: user.DeleteHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/api/v1/admin"),
	)
}
