// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: user.proto

package userclient

import (
	"context"

	"github.com/Dailiduzhou/weeklyLearningJournal/semester2/week10/zero-service/user/user/user"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	QueryReq       = user.QueryReq
	QueryResp      = user.QueryResp
	QueryResp_Post = user.QueryResp_Post

	User interface {
		Query(ctx context.Context, in *QueryReq, opts ...grpc.CallOption) (*QueryResp, error)
	}

	defaultUser struct {
		cli zrpc.Client
	}
)

func NewUser(cli zrpc.Client) User {
	return &defaultUser{
		cli: cli,
	}
}

func (m *defaultUser) Query(ctx context.Context, in *QueryReq, opts ...grpc.CallOption) (*QueryResp, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.Query(ctx, in, opts...)
}
